const CREATE_NEW_CHAPTERS = "CREATE_NEW_CHAPTERS";
const FETCH_BOOK_CHAPTERS = "FETCH_BOOK_CHAPTERS";
const CREATE_NEW_TAKEAWAYS = "CREATE_NEW_TAKEAWAYS";



export {
    FETCH_BOOK_CHAPTERS,
    CREATE_NEW_CHAPTERS,
    CREATE_NEW_TAKEAWAYS,
}