const FETCH_BOOK_DATA = "FETCH_BOOK_DATA";
const GET_SAVED_BOOKS_IDS = "GET_SAVED_BOOKS_IDS";
const ADD_BOOK = "ADD_BOOK";
const CREATE_NEW_CHAPTERS = "CREATE_NEW_CHAPTERS";
const FETCH_BOOK_CHAPTERS = "FETCH_BOOK_CHAPTERS";
const CREATE_NEW_TAKEAWAYS = "CREATE_NEW_TAKEAWAYS";
const FETCH_SINGLE_BOOK = "FETCH_SINGLE_BOOK";


export {
    FETCH_BOOK_CHAPTERS,
    FETCH_BOOK_DATA,
    FETCH_SINGLE_BOOK,
    GET_SAVED_BOOKS_IDS,
    ADD_BOOK,
    CREATE_NEW_CHAPTERS,
    CREATE_NEW_TAKEAWAYS,
}